services:
  bot:
    network_mode: host
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: python run.py
    environment:
      - TOKEN=${TOKEN}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}